### Matrix and Vectors

#### Matrix
Rectacular array of number    
Dimension of matrix: number of row x number of columns

$A_{ij} =$  "$i, j$ entry" of the $i^{th}$ row, $j^{th}$ column

$\begin{bmatrix}
A_{11} & A_{12} & A_{13} \\ A_{21} & A_{22} & A_{23} \\ A_{31} & A_{32} & A_{33}
\end{bmatrix}$

#### Vector
n x 1 matrix      
$y_i = i^{th}$ element

$\begin{bmatrix}y_1 \\ y_2 \\ y_3 \\ y_4\end{bmatrix}$    1-indexed vector  $\begin{bmatrix}y_0 \\ y_1 \\ y_2 \\ y_3\end{bmatrix}$    0-indexed vector

### Addition and Scalar Multiplication

#### Matrix Addition
$\begin{bmatrix}
A_{11} & A_{12} \\ A_{21} & A_{22} \\ A_{31} & A_{32}
\end{bmatrix}$ +
$\begin{bmatrix}
B_{11} & B_{12} \\ B_{21} & B_{22} \\ B_{31} & B_{32}
\end{bmatrix}$ =
$\begin{bmatrix}
A_{11} + B_{11} & A_{12} + B_{12} \\ A_{21} + B_{21} & A_{22} +  B_{22} \\ A_{31} + B_{31} & A_{32} + B_{32}
\end{bmatrix}$

$\begin{bmatrix}
A_{11} & A_{12} \\ A_{21} & A_{22} \\ A_{31} & A_{32}
\end{bmatrix}$ -
$\begin{bmatrix}
B_{11} & B_{12} \\ B_{21} & B_{22} \\ B_{31} & B_{32}
\end{bmatrix}$ =
$\begin{bmatrix}
A_{11} - B_{11} & A_{12} - B_{12} \\ A_{21} - B_{21} & A_{22} -  B_{22} \\ A_{31} - B_{31} & A_{32} - B_{32}
\end{bmatrix}$


#### Scalar Multiplication

$ a * \begin{bmatrix}
A_{11} & A_{12} \\ A_{21} & A_{22} \\ A_{31} & A_{32}
\end{bmatrix}$ = 
$\begin{bmatrix}
a * A_{11} & a * A_{12} \\ a * A_{21} & a * A_{22} \\ a * A_{31} & a * A_{32}
\end{bmatrix}$

$ \begin{bmatrix}
A_{11} & A_{12} \\ A_{21} & A_{22} \\ A_{31} & A_{32}
\end{bmatrix} / a$ = 
$\begin{bmatrix}
A_{11} / a & A_{12} / a \\ A_{21} / a & A_{22} / a \\ A_{31} / a & A_{32} / a
\end{bmatrix}$

In [34]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[100, 200], [300, 400]])
print(A + B)
print(10 * A)
print(10 + A)
print(A / 10)


[[101 202]
 [303 404]]
[[10 20]
 [30 40]]
[[11 12]
 [13 14]]
[[0.1 0.2]
 [0.3 0.4]]


### Matrix Vector Multiplication

$
\begin{bmatrix}
A_{11} & A_{12} \\ A_{21} & A_{22} \\ A_{31} & A_{32}
\end{bmatrix} * 
\begin{bmatrix}
x_{1} \\ x_{2}
\end{bmatrix} =
\begin{bmatrix}
A_{11} * x_{1}  + A_{12} * x_{2} \\ A_{21} * x_{1} + A_{22} * x_{2} \\ A_{31} * x_{1} + A_{32} * x_{2}
\end{bmatrix}
$

3 x 2 matrix $*$ 2 x 1 vector = 3 x 1    
m x n  $*$  n x p = m x p

#### Example
Houses sizes:
$x = \begin{bmatrix}2014 \\ 1416 \\ 1534 \\ 852 \end{bmatrix}$   $ h_\theta(x) = -40 + 0.25x $



$
\begin{bmatrix}
1 & 2014 \\ 1 & 1416 \\ 1 & 1534 \\ 1 & 852
\end{bmatrix} * 
\begin{bmatrix}
-40 \\ 0.25
\end{bmatrix} =
\begin{bmatrix}
-40 * 1  + 0.25 * 2014 \\ -40 * 1  + 0.25 * 1416 \\ -40 * 1  + 0.25 * * 1532 \\ -40 * 1  + 0.25 * * 852
\end{bmatrix}
$

In [26]:
import numpy as np

x = np.array([[1, 2104], [1, 1416], [1, 1534], [1, 852]])
h = np.array([-40, 0.25])
np.dot(x, h)

array([486. , 314. , 343.5, 173. ])

### Matrix Matrix Multiplication

$\begin{bmatrix}
A_{11} & A_{12} & A_{13} \\ A_{21} & A_{22} & A_{23} 
\end{bmatrix} * \begin{bmatrix}
B_{11} & B_{12} \\ B_{21} & B_{22} \\ B_{31} & B_{32}
\end{bmatrix} =
\begin{bmatrix}
A_{11} * B_{11}  + A_{12} * B_{21} + A_{13} * B_{31} & A_{11} * B_{12}  + A_{12} * B_{22} + A_{13} * B_{32} \\
A_{21} * B_{11}  + A_{22} * B_{21} + A_{23} * B_{31} & A_{21} * B_{12}  + A_{22} * B_{22} + A_{23} * B_{32}
\end{bmatrix}
$

In [27]:
houses_sizes = np.array([2104, 1416, 1534, 852])

h1 = lambda x: -40 + 0.25 * x
h2 = lambda x: -200 + 0.1 * x
h3 = lambda x: -150 + 0.4 * x

print(h1(houses_sizes))
print(h2(houses_sizes))
print(h3(houses_sizes))

# use matrix product to evaluate multiple hypothesis

houses_sizes = np.array([[1, 2104], [1, 1416], [1, 1534], [1, 852]])
h = np.array([[-40, -200, -150], [0.25, 0.1, 0.4]])
np.dot(houses_sizes, h)

[486.  314.  343.5 173. ]
[  10.4  -58.4  -46.6 -114.8]
[691.6 416.4 463.6 190.8]


array([[ 486. ,   10.4,  691.6],
       [ 314. ,  -58.4,  416.4],
       [ 343.5,  -46.6,  463.6],
       [ 173. , -114.8,  190.8]])

### Matrix Multiplication Properties

Let A and B be matrices, in general:  $A * B \neq B * A$

Associative property $(A * B) * C = A * (B * C)$

Identity matrix $I$ or $I_{n*n} $ , example  $I_{2*2} = \begin{bmatrix}1 & 0 \\ 0 & 1 \end{bmatrix}$

$A*I = I*A$

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Inverse and Transpose

#### Inverse
If A is m * n matrix and it has an inverse:   
$ A * A^{-1} = A^{-1} * A = I $

matrix that doesn't have an inverse are called "singular" or "degenerate"

In [29]:
A = np.array([[3, 4], [2, 16]])
A_inv = np.linalg.inv(A)
print(A_inv)

np.dot(A, A_inv)

[[ 0.4   -0.1  ]
 [-0.05   0.075]]


array([[1., 0.],
       [0., 1.]])

#### Transpose
Let $A$ be an m x n matrix, adn let $ B = A^T$, then b is n x m and $ B_{ij} = A_{ji} $
(Change row with columns or flip matrix over 45 degree axes)

In [30]:
A.T

array([[ 3,  2],
       [ 4, 16]])